[package]
name = "cairo_program_profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm = "1.0.1"
#cairo-vm = "0.4.0"

csv = "1.1"

[profile.release]
debug = true  # Enables debug symbols
